-- AKCIJE

INSERT INTO AKCIJA VALUES(1,'0','ADMIN');
INSERT INTO AKCIJA VALUES(2,'0','USER');


-- uloga

INSERT INTO ULOGA VALUES (1,'0','MOZE SVE');
INSERT INTO ULOGA VALUES (2,'0','EH');
INSERT INTO ULOGA VALUES (3,'0','EH3');
INSERT INTO ULOGA VALUES (4,'0','EH4');
INSERT INTO ULOGA VALUES (5,'0','EH5');

-- korisnik

INSERT INTO KORISNIK VALUES
(1,NULL ,NULL,'huma.milisic@gmail.com',TRUE,'HUMA',NULL ,NULL,'$2a$10$VrVNE6bFjI8GsLujFb2qquB8/jYqJiyuJ6aYUBr5Rdysp2u33wRsS','HUMA','huma' );

INSERT INTO KORISNIK VALUES
(2,NULL ,NULL,'1huma.milisic@gmail.com',TRUE,'HUMA',NULL ,NULL,'g','HUMA','humta' );

INSERT INTO KORISNIK VALUES
(3,NULL,NULL,'2huma.milisic@gmail.com',TRUE,'HUMA',NULL ,NULL,'$2a$10$VrVNE6bFjI8GsLujFb2qquB8/jYqJiyuJ6aYUBr5Rdysp2u33wRsS','HUMA','1huma' );

INSERT INTO KORISNIK VALUES
(4,NULL ,NULL,'3huma.milisic@gmail.com',TRUE,'HUMA',NULL ,NULL,'$2a$10$VrVNE6bFjI8GsLujFb2qquB8/jYqJiyuJ6aYUBr5Rdysp2u33wRsS','HUMA','2huma' );

INSERT INTO KORISNIK VALUES
(5,NULL,NULL,'4huma.milisic@gmail.com',TRUE,'HUMA',NULL ,NULL,'$2a$10$VrVNE6bFjI8GsLujFb2qquB8/jYqJiyuJ6aYUBr5Rdysp2u33wRsS','HUMA','3huma' );

INSERT INTO KORISNIK VALUES
(6,NULL,NULL,'5huma.milisic@gmail.com',TRUE,'HUMA',NULL ,NULL,'$2a$10$VrVNE6bFjI8GsLujFb2qquB8/jYqJiyuJ6aYUBr5Rdysp2u33wRsS','HUMA','4huma' );

INSERT INTO KORISNIK VALUES
(7,NULL,NULL,'6huma.milisic@gmail.com',TRUE,'HUMA',NULL ,NULL,'$2a$10$VrVNE6bFjI8GsLujFb2qquB8/jYqJiyuJ6aYUBr5Rdysp2u33wRsS','HUMA','h5uma' );

INSERT INTO KORISNIK VALUES
(8,NULL,NULL,'7huma.milisic@gmail.com',TRUE,'HUMA',NULL ,NULL,'$2a$10$VrVNE6bFjI8GsLujFb2qquB8/jYqJiyuJ6aYUBr5Rdysp2u33wRsS','HUMA','hu6ma' );

-- KORISNIK_X_ULOGA

INSERT INTO KORISNIK_X_ULOGA VALUES (1,1);
INSERT INTO KORISNIK_X_ULOGA VALUES (2,2);

-- ULOGA_X_AKCIJA

INSERT INTO ULOGA_X_AKCIJA
-- (uloga,akcija)
 VALUES (1,1);
INSERT INTO ULOGA_X_AKCIJA
-- (uloga,akcija)
 VALUES (2,1);